CREATE TABLE `xmcontent_content` (
  `content_id`            mediumint(8) unsigned NOT NULL AUTO_INCREMENT,
  `content_title`         varchar(100)          NOT NULL DEFAULT '',
  `content_text`          text                  NOT NULL,
  `content_status`        tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_mkeyword`      text                  NOT NULL,
  `content_mdescription`  text                  NOT NULL,
  `content_maindisplay`   tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_logo`          varchar(50)           NOT NULL DEFAULT '',
  `content_weight`        smallint(5)           NOT NULL DEFAULT '0',
  `content_css`           varchar(50)           NOT NULL DEFAULT '',
  `content_template`      varchar(50)           NOT NULL DEFAULT '',
  `content_docomment`     tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_dopdf`         tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_doprint`       tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_dosocial`      tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_domail`        tinyint(1)   unsigned NOT NULL DEFAULT '0',
  `content_dotitle`       tinyint(1)   unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`content_id`),
  KEY `content_title` (`content_title`)
) ENGINE=MyISAM;